fix bug for ucore i386 without SWAP feature. in the future, the defaut swap feature is not set. uCore_test has bug, so uCore_test and uCore_run reback to  9e2d79ba37

diff --git a/ucore/uCore_test b/ucore/uCore_test
--- a/ucore/uCore_test
+++ b/ucore/uCore_test
@@ -3,12 +3,11 @@
 stdout=/dev/stdout
 stderr=/dev/stderr
 
-BUILD_DIR=${BUILD_DIR:-obj}
+BUILD_DIR=obj
 RECORD_MODE=
 TEST_CASE=
 TIMEOUT=10
 WAIT_TIMEOUT=0
-MAX_PROCS=`grep processor /proc/cpuinfo | wc -l`
 
 DEFAULT_TEST=y
 UCORE_TEST_DIR=src/user-ucore
@@ -18,18 +17,15 @@ BIONIC_LIBC_TEST_ENABLED=
 : ${UCLIBC_TEST_DIR=../../ucore_lib_uclibc}
 UCLIBC_ENABLED=
 
+TEST_RESULT_DIR=
 BRK_FUNC=readline
 QEMU_SERIAL_LOG=serial.log
+TEST_SUITE_NAME=
 
-export SUMMARY=${SUMMARY:-$stdout}
+SUMMARY=$stdout
 TEST_LIST=testlist
-LOCK_FILENAME=.build-lock
 SPEC_TMP=.spec.tmp
 PATTERN_TMP=.pattern.tmp
-TOTAL_COUNT_TMP=.total.tmp
-PASSED_COUNT_TMP=.passed.tmp
-FAILED_COUNT_TMP=.failed.tmp
-BROKEN_COUNT_TMP=.broken.tmp
 
 SFSIMG_CLEAN=0
 
@@ -67,7 +63,7 @@ check_regexps() {
     reg=0
     error=
 
-    sed "/@.*$/d" $spec_file | sed "s/'/\n'/" | sed "s/^![ \t]*/!\n/" | sed "s/^-[ \t]*/-\n/" | sed "/^[[:space:]]*$/d" > $TEST_RESULT_DIR/$PATTERN_TMP.$$
+    sed "/@.*$/d" $spec_file | sed "s/'/\n'/" | sed "s/^![ \t]*/!\n/" | sed "s/^-[ \t]*/-\n/" | sed "/^[[:space:]]*$/d" > $TEST_RESULT_DIR/$PATTERN_TMP
     while read i; do
         if [ "x$i" = "x!" ]; then
             not=1
@@ -98,12 +94,18 @@ check_regexps() {
             not=0
             reg=0
         fi
-    done < $TEST_RESULT_DIR/$PATTERN_TMP.$$
+    done < $TEST_RESULT_DIR/$PATTERN_TMP
 
-    rm $TEST_RESULT_DIR/$PATTERN_TMP.$$
     if [ "$okay" = "yes" ]; then
+        printf "%10s\n" "[  PASS  ]" >> $SUMMARY
         return 0
     else
+        if [[ $HTML_OUTPUT = "y" ]]; then
+            printf "<font color=red><a href=\"%s\">%10s\n</a></font>" build-$UCONFIG_ARCH/$name.error "[  FAIL  ]" >> $SUMMARY
+        else
+            printf "%10s\n" "[  FAIL  ]" >> $SUMMARY
+        fi
+
         if [[ $RECORD_MODE != "y" ]]; then
             echo -e "$error" > $stderr
         else
@@ -114,32 +116,26 @@ check_regexps() {
     fi
 }
 
-# usage: print_info <test name> <result>
-print_result() {
-    printf "%-60s%10s\n" "TEST <$TEST_SUITE_NAME> $1" "$2" >> $SUMMARY
-}
-
-# usage: acquire_lock <lock file path>
-acquire_lock() {
-    lockfile $1
-}
-
-# usage: release_lock <lock file path>
-release_lock() {
-    rm -r $1
-}
-
 # usage: run_test <testspec path>
 run_test() {
     TEST_SPEC=$1
-    name=`basename $TEST_SPEC .testspec`
-    source $BUILD_DIR/config/auto.conf
+
+    grep "^@sfs_force_rebuild[ \t]*$" $TEST_SPEC > /dev/null 2>&1
+    found=$(($? == 0))
+    if [ $found -eq 1 ] && [ $SFSIMG_CLEAN -ne 1 ]; then
+	# FIXME: The arguments here are dummy
+	# It won't work if any test case other than those with uCore requires to rebuild the image
+        rebuild_testimg $UCORE_TEST_DIR sfs-orig.img
+        if [ $? -ne 0 ]; then
+            return 1
+        fi
+    fi
 
     arch=
     timeout=
     program=
-    grep "^@.*" $TEST_SPEC | sed "s/^@\([A-Za-z0-9_]*\)[ \t]*\(.*\)$/\1=\"\2\"/g" > $TEST_RESULT_DIR/$SPEC_TMP.$$
-    source $TEST_RESULT_DIR/$SPEC_TMP.$$
+    grep "^@.*" $TEST_SPEC | sed "s/^@\([A-Za-z0-9_]*\)[ \t]*\(.*\)$/\1=\"\2\"/g" > $TEST_RESULT_DIR/$SPEC_TMP
+    source $TEST_RESULT_DIR/$SPEC_TMP
     if [ -z $program ]; then
         return 10
     fi
@@ -149,77 +145,42 @@ run_test() {
             return 10
         fi
     fi
+    name=`basename $TEST_SPEC .testspec`
     if [ -z "$timeout" ] || [ $timeout -gt 600 ]; then
         timeout=$TIMEOUT
     fi
 
     export UCORE_TEST=$program
-    echo -n . >> $BUILD_DIR/$TOTAL_COUNT_TMP
-
-    acquire_lock $BUILD_DIR/$LOCK_FILENAME
-    grep "^@sfs_force_rebuild[ \t]*$" $TEST_SPEC > /dev/null 2>&1
-    found=$(($? == 0))
-    if [ $found -eq 1 ] && [ $SFSIMG_CLEAN -ne 1 ]; then
-	# FIXME: The arguments here are dummy
-	# It won't work if any test case other than those with uCore requires to rebuild the image
-        rebuild_testimg $UCORE_TEST_DIR sfs-orig.img
-        if [ $? -ne 0 ]; then
-	    print_result $name "[  BROKEN  ]"
-	    echo -n . >> $BUILD_DIR/$BROKEN_COUNT_TMP
-	    return 1
-        fi
-	cp $BUILD_DIR/sfs.img $BUILD_DIR/sfs.img.$$
-    else
-	ln -s sfs.img $BUILD_DIR/sfs.img.$$
-    fi
+    printf "%-70s" "TEST <$TEST_SUITE_NAME> $name " >> $SUMMARY
 
     make O=$BUILD_DIR > /dev/null 2>&1
-    result=$?
-    cp $BUILD_DIR/kernel.img $BUILD_DIR/kernel.img.$$ 2>/dev/null
-    cp $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf.$$
-    release_lock $BUILD_DIR/$LOCK_FILENAME
-    if [ $result -ne 0 ]; then
-	print_result $name "[ BROKEN ]"
-	echo -n . >> $BUILD_DIR/$BROKEN_COUNT_TMP
+    if [ $? -ne 0 ]; then
+        printf "%10s\n" "[ BROKEN ]" >> $SUMMARY
         exit 1
     fi
 
     (
         ulimit -t $timeout
-	exec ./uCore_run -d $BUILD_DIR -t $$
+        exec ./uCore_run -d $BUILD_DIR -t
     ) > /dev/null 2>&1 &
     pid=$!
     sleep $WAIT_TIMEOUT
-    "$UCONFIG_CROSS_COMPILE"gdb -batch -nx \
-        -ex "target remote :$[ $$ % 10000 + 40000 ]" \
-        -ex "file $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf.$$"  \
+    "$UCONFIG_CROSS_COMPILE"gdb -batch -nx -x gdbinit.$UCONFIG_ARCH \
+        -ex "file $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf"  \
         -ex "b $BRK_FUNC" \
         -ex "c" > /dev/null 2>&1
 
     kill $pid > /dev/null 2>&1
     SFSIMG_CLEAN=0
 
-    check_regexps $BUILD_DIR/$QEMU_SERIAL_LOG.$$ $TEST_SPEC
-    case $? in
-	0)
-	    print_result $name "[  PASS  ]"
-	    echo -n . >> $BUILD_DIR/$PASSED_COUNT_TMP
-	    ;;
-	1)
-	    print_result $name "[  FAIL  ]"
-	    echo -n . >> $BUILD_DIR/$FAILED_COUNT_TMP
-	    ;;
-    esac
-
-    rm $BUILD_DIR/kernel.img.$$ 2>/dev/null
-    rm $BUILD_DIR/sfs.img.$$
-    rm $BUILD_DIR/serial.log.$$
-    rm $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf.$$
-    rm $TEST_RESULT_DIR/$SPEC_TMP.$$
+    check_regexps $BUILD_DIR/$QEMU_SERIAL_LOG $TEST_SPEC
+    TEST_RESULT=$?
 
     if [[ $RECORD_MODE = "y" ]]; then
         tail -n 1 $SUMMARY
     fi
+
+    return $TEST_RESULT
 }
 
 # usage: run_test_suite <name> <src dir> <output file name>
@@ -227,7 +188,7 @@ run_test_suite() {
     if [ -z $3 ]; then
         return 1
     fi
-    export TEST_SUITE_NAME=$1
+    TEST_SUITE_NAME=$1
     rebuild_testimg $2 $BUILD_DIR/$3
     if [ $? -ne 0 ]; then
         return 1;
@@ -242,13 +203,27 @@ run_test_suite() {
     else
         find $2/testspecs | grep "\.testspec$" | sort > $TEST_RESULT_DIR/$TEST_LIST
     fi
-    cat $TEST_RESULT_DIR/$TEST_LIST | xargs --max-procs=$MAX_PROCS -n 1 "$0" -1
+    while read spec; do
+        TOTAL=$(( ++TOTAL ))
+        run_test $spec
+        case $? in
+            0)
+                PASSED=$(( ++PASSED ))
+                ;;
+            1)
+                FAILED=$(( ++FAILED ))
+                ;;
+            10)
+                TOTAL=$(( --TOTAL ))
+                ;;
+        esac
+    done < $TEST_RESULT_DIR/$TEST_LIST
 }
 
-while getopts "d:f:hrs:t:w:1:" opt; do
+while getopts "d:f:hrs:t:w:" opt; do
     case $opt in
         d)
-            export BUILD_DIR=$OPTARG
+            BUILD_DIR=$OPTARG
             ;;
         f)
             TEST_CASE=$OPTARG
@@ -308,11 +283,6 @@ while getopts "d:f:hrs:t:w:1:" opt; do
         o)
             HTML_OUTPUT=y
 	    ;;
-	1)
-	    # This is a private option which should only be used in the script itself
-	    run_test $OPTARG
-	    exit $?
-	    ;;
         ?)
             exit 1
             ;;
@@ -325,10 +295,10 @@ fi
 
 TIMESTAMP=`date +%Y%m%d-%H%M%S`
 if [[ $RECORD_MODE = "y" ]]; then
-    export TEST_RESULT_DIR=$BUILD_DIR/test-result.$TIMESTAMP
-    export SUMMARY=$TEST_RESULT_DIR/summary
+    TEST_RESULT_DIR=$BUILD_DIR/test-result.$TIMESTAMP
+    SUMMARY=$TEST_RESULT_DIR/summary
 else
-    export TEST_RESULT_DIR=/tmp/uCore_test
+    TEST_RESULT_DIR=/tmp/uCore_test
 fi
 mkdir -p $TEST_RESULT_DIR
 if [[ $RECORD_MODE = "y" ]]; then
@@ -337,10 +307,9 @@ fi
 
 source $BUILD_DIR/config/auto.conf
 
-touch $BUILD_DIR/$TOTAL_COUNT_TMP
-touch $BUILD_DIR/$PASSED_COUNT_TMP
-touch $BUILD_DIR/$FAILED_COUNT_TMP
-touch $BUILD_DIR/$BROKEN_COUNT_TMP
+TOTAL=0
+PASSED=0
+FAILED=0
 
 # uCore builtin test suite
 if [[ $UCORE_TEST_ENABLED = "y" ]] && [ -e $UCORE_TEST_DIR ]; then
@@ -358,14 +327,11 @@ if [[ $UCLIBC_TEST_ENABLED = "y" ]] && [ -e $UCLIBC_TEST_DIR ]; then
 fi
 
 echo "========== Test Summary ==========" >> $SUMMARY
-echo "  Total   " `cat $BUILD_DIR/$TOTAL_COUNT_TMP | wc -m` >> $SUMMARY
-echo "  Passed  " `cat $BUILD_DIR/$PASSED_COUNT_TMP | wc -m` >> $SUMMARY
-echo "  Failed  " `cat $BUILD_DIR/$FAILED_COUNT_TMP | wc -m` >> $SUMMARY
-echo "  Broken  " `cat $BUILD_DIR/$BROKEN_COUNT_TMP | wc -m` >> $SUMMARY
+echo "  Total   $TOTAL" >> $SUMMARY
+echo "  Passed  $PASSED" >> $SUMMARY
+echo "  Failed  $FAILED" >> $SUMMARY
 echo "==================================" >> $SUMMARY
 
-rm -f $BUILD_DIR/$TOTAL_COUNT_TMP $BUILD_DIR/$PASSED_COUNT_TMP $BUILD_DIR/$FAILED_COUNT_TMP $BUILD_DIR/$BROKEN_COUNT_TMP
-
 if [[ $RECORD_MODE = "y" ]]; then
-    tail -n 6 $SUMMARY
+    tail -n 5 $SUMMARY
 fi
