Replace tabs with spaces in the run/test scripts.
Signed-off-by: Junjie Mao <eternal.n08@gmail.com>

diff --git a/ucore/uCore_test b/ucore/uCore_test
--- a/ucore/uCore_test
+++ b/ucore/uCore_test
@@ -31,48 +31,48 @@ check_regexps() {
 
     sed "/@.*$/d" $spec_file | sed "s/'/\n'/" | sed "s/^![ \t]*/!\n/" | sed "s/^-[ \t]*/-\n/" | sed "/^[[:space:]]*$/d" > $TEST_RESULT_DIR/$PATTERN_TMP
     while read i; do
-	if [ "x$i" = "x!" ]; then
-	    not=1
-	elif [ "x$i" = "x-" ]; then
-	    reg=1
-	else
-	    pattern=${i//\'/}
-	    if [ $reg -ne 0 ]; then
-		grep '-E' "^$pattern\$" $log > /dev/null
-	    else
-		grep '-F' "$pattern" $log > /dev/null
-	    fi
-	    found=$(($? == 0))
-	    if [ $found -eq $not ]; then
-		if [ $found -eq 0 ]; then
-		    msg="!! error: missing '$pattern'"
-		else
-		    msg="!! error: got unexpected line '$pattern'"
-		fi
-		okay=no
-		if [ -z "$error" ]; then
-		    error="$msg"
-		else
-		    error="$error\n$msg"
-		fi
-	    fi
-	    not=0
-	    reg=0
-	fi
+        if [ "x$i" = "x!" ]; then
+            not=1
+        elif [ "x$i" = "x-" ]; then
+            reg=1
+        else
+            pattern=${i//\'/}
+            if [ $reg -ne 0 ]; then
+                grep '-E' "^$pattern\$" $log > /dev/null
+            else
+                grep '-F' "$pattern" $log > /dev/null
+            fi
+            found=$(($? == 0))
+            if [ $found -eq $not ]; then
+                if [ $found -eq 0 ]; then
+                    msg="!! error: missing '$pattern'"
+                else
+                    msg="!! error: got unexpected line '$pattern'"
+                fi
+                okay=no
+                if [ -z "$error" ]; then
+                    error="$msg"
+                else
+                    error="$error\n$msg"
+                fi
+            fi
+            not=0
+            reg=0
+        fi
     done < $TEST_RESULT_DIR/$PATTERN_TMP
 
     if [ "$okay" = "yes" ]; then
-	printf "%10s\n" "[  PASS  ]" >> $SUMMARY
-	return 0
+        printf "%10s\n" "[  PASS  ]" >> $SUMMARY
+        return 0
     else
-	printf "%10s\n" "[  FAIL  ]" >> $SUMMARY
-	if [[ $RECORD_MODE != "y" ]]; then
-	    echo -e "$error" > $stderr
-	else
-	    echo -e "$error" > $TEST_RESULT_DIR/$name.error
-	    cp $log $TEST_RESULT_DIR/$name.log
-	fi
-	return 1
+        printf "%10s\n" "[  FAIL  ]" >> $SUMMARY
+        if [[ $RECORD_MODE != "y" ]]; then
+            echo -e "$error" > $stderr
+        else
+            echo -e "$error" > $TEST_RESULT_DIR/$name.error
+            cp $log $TEST_RESULT_DIR/$name.log
+        fi
+        return 1
     fi
 }
 
@@ -96,19 +96,19 @@ run_test() {
 
     make O=$BUILD_DIR > /dev/null 2>&1
     if [ $? -ne 0 ]; then
-	printf "%10s\n" "[ BROKEN ]" >> $SUMMARY
-	exit 1
+        printf "%10s\n" "[ BROKEN ]" >> $SUMMARY
+        exit 1
     fi
 
     (
-	ulimit -t $TIMEOUT
-	exec ./uCore_run -d $BUILD_DIR -t
+        ulimit -t $TIMEOUT
+        exec ./uCore_run -d $BUILD_DIR -t
     ) > /dev/null 2>&1 &
     pid=$!
     gdb -batch -nx -x gdbinit.$UCONFIG_ARCH \
-	-ex "file $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf"  \
-	-ex "b $BRK_FUNC" \
-	-ex "c" > /dev/null 2>&1
+        -ex "file $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf"  \
+        -ex "b $BRK_FUNC" \
+        -ex "c" > /dev/null 2>&1
 
     kill $pid > /dev/null 2>&1
 
@@ -116,7 +116,7 @@ run_test() {
     TEST_RESULT=$?
 
     if [[ $RECORD_MODE = "y" ]]; then
-	tail -n 1 $SUMMARY
+        tail -n 1 $SUMMARY
     fi
 
     return $TEST_RESULT
@@ -124,45 +124,45 @@ run_test() {
 
 while getopts "d:f:hrst:" opt; do
     case $opt in
-	d)
-	    BUILD_DIR=$OPTARG
-	    ;;
-	f)
-	    TEST_CASE=$OPTARG
-	    ;;
-	h)
-	    echo "Usage $0 [options]"
-	    echo "Options:"
-	    echo "  -d <directory>               uCore build directory                            "
-	    echo "                               default to obj/                                  "
-	    echo "  -f <spec file>               Run the test given                               "
-	    echo "  -r                           Record error messages in the build               "
-	    echo "                               dir and do not print them on stderr              "
-	    echo "  -s                           Do not rebuild sfsimg                            "
-	    echo "  -t <timeout>                 How long each test instance can live in seconds  "
-	    echo "                               default to 10                                    "
-	    echo "                                                                                "
-	    echo "This script is platform-independent.                                            "
-	    echo "See './uCore_run -h' for supported platforms.                                   "
-	    echo "                                                                                "
-	    echo "Report bugs to https://github.com/chyyuu/ucore_plus/issues                      "
-	    exit 0
-	    ;;
-	r)
-	    RECORD_MODE=y
-	    ;;
-	s)
-	    NO_BUILD_SFSIMG=y
-	    ;;
-	t)
-	    case $OPTARG in
-		''|*[!0-9]*) echo "WARNING: Bad number: $OPTARG" ;;
-		*) TIMEOUT=$OPTARG ;;
-	    esac
-	    ;;
-	?)
-	    exit 1
-	    ;;
+        d)
+            BUILD_DIR=$OPTARG
+            ;;
+        f)
+            TEST_CASE=$OPTARG
+            ;;
+        h)
+            echo "Usage $0 [options]"
+            echo "Options:"
+            echo "  -d <directory>               uCore build directory                            "
+            echo "                               default to obj/                                  "
+            echo "  -f <spec file>               Run the test given                               "
+            echo "  -r                           Record error messages in the build               "
+            echo "                               dir and do not print them on stderr              "
+            echo "  -s                           Do not rebuild sfsimg                            "
+            echo "  -t <timeout>                 How long each test instance can live in seconds  "
+            echo "                               default to 10                                    "
+            echo "                                                                                "
+            echo "This script is platform-independent.                                            "
+            echo "See './uCore_run -h' for supported platforms.                                   "
+            echo "                                                                                "
+            echo "Report bugs to https://github.com/chyyuu/ucore_plus/issues                      "
+            exit 0
+            ;;
+        r)
+            RECORD_MODE=y
+            ;;
+        s)
+            NO_BUILD_SFSIMG=y
+            ;;
+        t)
+            case $OPTARG in
+                ''|*[!0-9]*) echo "WARNING: Bad number: $OPTARG" ;;
+                *) TIMEOUT=$OPTARG ;;
+            esac
+            ;;
+        ?)
+            exit 1
+            ;;
     esac
 done
 
@@ -184,17 +184,17 @@ FAILED=0
 if [[ $NO_BUILD_SFSIMG != "y" ]]; then
     UCORE_TEST=xx make O=$BUILD_DIR sfsimg > /dev/null 2>&1
     if [ $? -ne 0 ]; then
-	echo "Cannot build sfsimg with unit tests!" > $stderr
-	exit 1
+        echo "Cannot build sfsimg with unit tests!" > $stderr
+        exit 1
     fi
 fi
 
 if [[ $TEST_CASE != "" ]]; then
     if [ -f $TEST_CASE ]; then
-	echo $TEST_CASE > $TEST_RESULT_DIR/$TEST_LIST
+        echo $TEST_CASE > $TEST_RESULT_DIR/$TEST_LIST
     else
-	echo "Spec file $TEST_CASE does not exist!" > $stderr
-	exit 1
+        echo "Spec file $TEST_CASE does not exist!" > $stderr
+        exit 1
     fi
 else
     find $TEST_SRC_DIR -name "*.testspec" > $TEST_RESULT_DIR/$TEST_LIST
